### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by ju-sh** [ejgallego/pycoq#18]
I came across this project while searching for a way to parse coq source documents using Python (there is no pre-existing way for that, is there?).

But had trouble installing. I guess it's something trivial, but couldn't figure it out.

I tried

```
$ opam install --deps-only coq-serapi
Nothing to do.

$ opam install pythonlib
[NOTE] Package pythonlib is already installed (current version is v0.14.0).

$ make && dune build examples/test.py && dune exec -- python3 _build/default/examples/test.py
targets {build,python,test,clean}
Traceback (most recent call last):
  File "_build/default/examples/test.py", line 1, in <module>
    import pycoq, coq
ModuleNotFoundError: No module named 'pycoq'
```

The project at https://pypi.org/project/pycoq/ is not same as this, right?

**Comment by ejgallego** [comment]
Hi @ju-sh , yes, you are in the right place I think! API is pretty experimental but should work for you.

Sorry about the bug, instructions were out of date, first command needs to be `make install` now.

[I'm not sure how to best call pip3]

> The project at https://pypi.org/project/pycoq/ is not same as this, right?

Nope, that unfortunate, we named this before learning about it; tho the two projects are similar and in a sense this superseedes that one so we hope to fix the naming issue before a first release.
